### PR TITLE
Update 2021.07+fslc to v2021.07-rc5

### PR DESCRIPTION
**Pull request by zandrey**
Update local _U-Boot_ repository with `v2021.07-rc4` from DENX repository.

Following conflicts were manually resolved:
`configs/imx8mm_evk_defconfig`:
`configs/imx8mn_ddr4_evk_defconfig`:
`configs/imx8mn_evk_defconfig`:
`configs/imx8mp_evk_defconfig`:
Drop our local change, which are incuded in the commit 2bba780 ("configs: Resync with savedefconfig") from upstream.

`configs/mx6sabresd_defconfig`:
Merge changes from commit 2f7d389 ("mx6sabre_common: Dynamically change the video output") with upstream commit 2bba780 ("configs: Resync with savedefconfig").

Link: https://lore.kernel.org/u-boot/20210628194137.GU9516@bill-the-cat/

### CODE REVIEW

**Comment by fabioestevam** [comment]
Hi Andrey,

On Wed, Jun 30, 2021 at 8:02 AM Andrey Zhizhikin
***@***.***> wrote:
>
> Update local U-Boot repository with v2021.07-rc4 from DENX repository.
>
> Following conflicts were manually resolved:
> configs/imx8mm_evk_defconfig:
> configs/imx8mn_ddr4_evk_defconfig:
> configs/imx8mn_evk_defconfig:
> configs/imx8mp_evk_defconfig:
> Drop our local change, which are incuded in the commit 2bba780 ("configs: Resync with savedefconfig") from upstream.
>
> configs/mx6sabresd_defconfig:
> Merge changes from commit 2f7d389 ("mx6sabre_common: Dynamically change the video output") with upstream commit 2bba780 ("configs: Resync with savedefconfig").

Shouldn't we drop 2f7d389 ("mx6sabre_common: Dynamically change the
video output")?

This commit is an old one and it does not affect mainline kernels.

Regards,

Fabio Estevam

**Comment by zandrey** [comment]
Hello Fabio,

On Wed, Jun 30, 2021 at 1:13 PM fabioestevam ***@***.***> wrote:
>
> Hi Andrey,
>
> On Wed, Jun 30, 2021 at 8:02 AM Andrey Zhizhikin
> ***@***.***> wrote:
> >
> > Update local U-Boot repository with v2021.07-rc4 from DENX repository.
> >
> > Following conflicts were manually resolved:
> > configs/imx8mm_evk_defconfig:
> > configs/imx8mn_ddr4_evk_defconfig:
> > configs/imx8mn_evk_defconfig:
> > configs/imx8mp_evk_defconfig:
> > Drop our local change, which are incuded in the commit 2bba780 ("configs: Resync with savedefconfig") from upstream.
> >
> > configs/mx6sabresd_defconfig:
> > Merge changes from commit 2f7d389 ("mx6sabre_common: Dynamically change the video output") with upstream commit 2bba780 ("configs: Resync with savedefconfig").
>
> Shouldn't we drop 2f7d389 ("mx6sabre_common: Dynamically change the
> video output")?
>
> This commit is an old one and it does not affect mainline kernels.

Good point, I was not aware that this commit is not required anymore.
It was introduced by Otavio at the creation of 2021.07+fslc branch,
and I just stumbled upon it now when I merged the -rc5.

If there would be no objections from community, I can revert it on
2021.07+fslc branch when the final v2021.07 is released upstream
(target date is July, 5) and I would be merging it. New 2021.10+fslc
branch should not have this commit cherry-picked then.

>
> Regards,
>
> Fabio Estevam
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.


-- 
Regards,
Andrey.

**Comment by otavio** [comment]
I'm merging it now. Regarding the 2f7d389 ("mx6sabre_common: Dynamically change the video output") patch I wonder if it indeed unused. If so we ought to remove the `video_args_xxx` variables.

@fabioestevam what do you think?

**Comment by fabioestevam** [comment]
Hi Otavio,

On Wed, Jun 30, 2021 at 8:46 AM Otavio Salvador
***@***.***> wrote:
>
> I'm merging it now. Regarding the 2f7d389 ("mx6sabre_common: Dynamically change the video output") patch I wonder if it indeed unused. If so we ought to remove the video_args_xxx variables.
>
> @fabioestevam what do you think?

I am in favor of removing such a commit.

BTW, can we get a list of all the extra commits that are applied
against 2021.07-rc5?

I think we could have a look and discard the ones we don't need
anymore or try to upstream the ones we need for 2021.10.

Thanks

**Comment by zandrey** [comment]
Hello Fabio,

On Wed, Jun 30, 2021 at 1:54 PM fabioestevam ***@***.***> wrote:
>
> Hi Otavio,
>
> On Wed, Jun 30, 2021 at 8:46 AM Otavio Salvador
> ***@***.***> wrote:
> >
> > I'm merging it now. Regarding the 2f7d389 ("mx6sabre_common: Dynamically change the video output") patch I wonder if it indeed unused. If so we ought to remove the video_args_xxx variables.
> >
> > @fabioestevam what do you think?
>
> I am in favor of removing such a commit.
>
> BTW, can we get a list of all the extra commits that are applied
> against 2021.07-rc5?
>
> I think we could have a look and discard the ones we don't need
> anymore or try to upstream the ones we need for 2021.10.

Sure thing, here you go:
$ git log --no-merges --pretty=format:'%h ("%s")'
u-boot-denx/master..origin/2021.07+fslc
b047e1dcd2 ("arm: imx: imx8mm: correct unrecognized fracpll frequency")
13de33cc12 ("imx8mn: configs: add support for distro boot commands")
408376bd68 ("imx8mp: configs: enable distro default features")
5102ca18c1 ("imx8mm: configs: enable distro default features")
2d107f6d15 ("imx: iMX6: Define disconnect_from_pc function")
560a81e9cb ("MLK-21854-2 imx: uuu: Update autoboot to run uuu or fastboot")
81e786caa1 ("pico-imx6ul, pico-imx7d: Explain how to use eMMC user partition")
2f7d3890b6 ("mx6sabre_common: Dynamically change the video output")
6b4b7e030e ("mx6sabresd: Enable video interfaces in bootargs")

First 4 commits are from me, and they are already dropped as upstream
has accepted my patches. All the rest is from different authors.

>
> Thanks
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Regards,
Andrey.

**Comment by fabioestevam** [comment]
Hi Andrey and Otavio,

On Wed, Jun 30, 2021 at 9:02 AM Andrey Zhizhikin
***@***.***> wrote:

> Sure thing, here you go:

Thanks for sharing the list of additional patches, Andrey.

Glad to see the delta is not huge.

> $ git log --no-merges --pretty=format:'%h ("%s")'
> u-boot-denx/master..origin/2021.07+fslc
> b047e1dcd2 ("arm: imx: imx8mm: correct unrecognized fracpll frequency")
> 13de33cc12 ("imx8mn: configs: add support for distro boot commands")
> 408376bd68 ("imx8mp: configs: enable distro default features")
> 5102ca18c1 ("imx8mm: configs: enable distro default features")

These will be part of U-Boot 2021.07, great.

> 2d107f6d15 ("imx: iMX6: Define disconnect_from_pc function")

The commit log does not provide an explanation as to why this is needed.

I don't see disconnect_from_pc() being called anywhere.

Looks like a candidate for removal?

> 560a81e9cb ("MLK-21854-2 imx: uuu: Update autoboot to run uuu or fastboot")

What would be the impact of not applying this one? Are we relying on
the behavior provided by this patch?

> 81e786caa1 ("pico-imx6ul, pico-imx7d: Explain how to use eMMC user partition")

This one is a simple README update and could be upstreamed.

> 2f7d3890b6 ("mx6sabre_common: Dynamically change the video output")

This one we have discussed earlier today. We can drop it IMHO.

> 6b4b7e030e ("mx6sabresd: Enable video interfaces in bootargs")

This one sets the video kernel command line for old NXP kernels.

We should drop it as they do not affect mainline kernels.

Thanks,

Fabio Estevam

**Comment by fabioestevam** [comment]
On Wed, Jun 30, 2021 at 12:51 PM Fabio Estevam ***@***.***> wrote:

> > 2d107f6d15 ("imx: iMX6: Define disconnect_from_pc function")
>
> The commit log does not provide an explanation as to why this is needed.
>
> I don't see disconnect_from_pc() being called anywhere.

Ah, now I see. It is called by this commit:
https://github.com/Freescale/u-boot-fslc/commit/560a81e9cb

**Comment by zandrey** [comment]
Hello Fabio,

On Wed, Jun 30, 2021 at 5:52 PM fabioestevam ***@***.***> wrote:
>
> Hi Andrey and Otavio,
>
> On Wed, Jun 30, 2021 at 9:02 AM Andrey Zhizhikin
> ***@***.***> wrote:
>
> > Sure thing, here you go:
>
> Thanks for sharing the list of additional patches, Andrey.
>
> Glad to see the delta is not huge.
>
> > $ git log --no-merges --pretty=format:'%h ("%s")'
> > u-boot-denx/master..origin/2021.07+fslc
> > b047e1dcd2 ("arm: imx: imx8mm: correct unrecognized fracpll frequency")
> > 13de33cc12 ("imx8mn: configs: add support for distro boot commands")
> > 408376bd68 ("imx8mp: configs: enable distro default features")
> > 5102ca18c1 ("imx8mm: configs: enable distro default features")
>
> These will be part of U-Boot 2021.07, great.
>
> > 2d107f6d15 ("imx: iMX6: Define disconnect_from_pc function")
>
> The commit log does not provide an explanation as to why this is needed.
>
> I don't see disconnect_from_pc() being called anywhere.
>
> Looks like a candidate for removal?
>
> > 560a81e9cb ("MLK-21854-2 imx: uuu: Update autoboot to run uuu or fastboot")
>
> What would be the impact of not applying this one? Are we relying on
> the behavior provided by this patch?

This is an interesting way of piggy-backing the autoboot command and
re-diverting the boot sequence purely based on the fact that the
device is connected to the PC via USB...

I guess both commits should be re-worked in a way it does not stand in
a way of normal boot flow and rather use some additional logic to
re-direct the boot flow to either UUU or fastboot.

Commit 2d107f6d15 ("imx: iMX6: Define disconnect_from_pc function")
can be kept as-is, since it does not stand in a way of boot flow. But
I would rather see this as a separate 'usb' command to be able to call
this from the script.

Commit 560a81e9cb ("MLK-21854-2 imx: uuu: Update autoboot to run uuu
or fastboot") should be re-worked IMO, perhaps utilizing "distro boot"
functionality would be an option here.

What do you think about it?

>
> > 81e786caa1 ("pico-imx6ul, pico-imx7d: Explain how to use eMMC user partition")
>
> This one is a simple README update and could be upstreamed.
>
> > 2f7d3890b6 ("mx6sabre_common: Dynamically change the video output")
>
> This one we have discussed earlier today. We can drop it IMHO.
>
> > 6b4b7e030e ("mx6sabresd: Enable video interfaces in bootargs")
>
> This one sets the video kernel command line for old NXP kernels.
>
> We should drop it as they do not affect mainline kernels.
>
> Thanks,
>
> Fabio Estevam
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.


-- 
Regards,
Andrey.

**Comment by fabioestevam** [comment]
Hi Andrey,

On Wed, Jun 30, 2021 at 1:24 PM Andrey Zhizhikin
***@***.***> wrote:

> This is an interesting way of piggy-backing the autoboot command and
> re-diverting the boot sequence purely based on the fact that the
> device is connected to the PC via USB...
>
> I guess both commits should be re-worked in a way it does not stand in
> a way of normal boot flow and rather use some additional logic to
> re-direct the boot flow to either UUU or fastboot.

Agreed. That would be better indeed.

> Commit 2d107f6d15 ("imx: iMX6: Define disconnect_from_pc function")
> can be kept as-is, since it does not stand in a way of boot flow. But
> I would rather see this as a separate 'usb' command to be able to call
> this from the script.

Agreed.

> Commit 560a81e9cb ("MLK-21854-2 imx: uuu: Update autoboot to run uuu
> or fastboot") should be re-worked IMO, perhaps utilizing "distro boot"
> functionality would be an option here.
>
> What do you think about it?

It makes sense, thanks.

**Pull request merged**
