### PR TITLE
Add support for i.MX6 SD/MMC manufacturing mode

### PR DESCRIPTION
**Pull request by jaydcarlson**
This PR adds support for booting a blank i.MX6 device from an MMC or SD card connected to USDHC1 via the "SD/MMC Manufacture Mode" feature available on some i.MX6 devices. To support this, we check that both BOOT_MODE == 0 and that BT_FUSE_SEL == 0. 

This was tested on an i.MX6UL. Note that, unlike normal download, the SD/MMC Manufacture Mode checks the chip detect signal (which is bonded out to ball UART1_RTS_B), so if you're interested in using this mode to boot a blank i.MX6UL, make sure this signal is grounded.

### CODE REVIEW

**Review by otavio — CHANGES_REQUESTED** [review]
Few things which might be improved:

* commit log does not follow the guidelines from U-Boot community
* the commit log does not explain what it provides

Also, it is not clear if this is supported by all SoC families or just UL.

@jaydcarlson did you send this patch for mainline review?

**Comment by fabioestevam** [comment]
On Wed, May 23, 2018 at 9:11 AM, Otavio Salvador <notifications@github.com>
wrote:

> @otavio <https://github.com/otavio> requested your review on:
> Freescale/u-boot-fslc#25
> <https://github.com/Freescale/u-boot-fslc/pull/25> Add support for i.MX6
> SD/MMC manufacturing mode.
>
Both patches look good from a quick glance. Please send them for review to
the u-boot list.

**Comment by jaydcarlson** [comment]
Oh, sorry about that! I assumed i.MX-specific changes were submitted here and then pushed upstream. I've submitted both PRs as patches to the u-boot list as you requested.

**Comment by otavio** [comment]
This seems to have been merged on mainline, so I am closing it here.

**Comment by jaydcarlson** [comment]
Really? I don't see this commit in the master branch of the official u-boot git tree, or in u-boot-fslc. Did this functionality get wrapped up into something different, or is it on a different branch?

I submitted this patch to the u-boot mailing list, but never heard back.

**Comment by otavio** [comment]
@jaydcarlson sorry for the confusion. Please rebase your branch and resend it here and to upstream. It wasn't indeed merged.

**Comment by angolini** [comment]
Hi @jaydcarlson and @otavio, what is the status for this PR? Can we close it already?

**Comment by jaydcarlson** [comment]
Just opening this project for the first time in a while and saw this PR still hasn't made it in. It looks like there was a small conflict, but I fixed it. Can someone merge this now?

**Comment by jaydcarlson** [comment]
I rebased this as a new PR, so I'm closing this.

**Pull request closed without merging**
