### PR TITLE
pico-imx7d: Add support for secure boot

### PR DESCRIPTION
**Pull request by vanmaegima**
Add a new defconfig to enable secure boot on pico-imx7d.

Signed-off-by: Vanessa Maegima <vanessa.maegima@nxp.com>

### CODE REVIEW

**Comment by otavio** [comment]
@vanmaegima did you close it by purpose?

**Comment by vanmaegima** [comment]
@otavio I added the secure boot support to enable booting with linux-fslc to add the support for pico-imx7d on meta-freescale. Fabio made an observation that secure boot is not a requirement to boot with linux-fslc 4.9 so I closed it.

**Comment by otavio** [comment]
I think it is a valid addition. Also it should be send upstream

**Comment by vanmaegima** [comment]
I'll reopen it.

**Pull request merged**
