### PR TITLE
add sdhc auto-detection at boot time for pico-imx7d

### PR DESCRIPTION
**Pull request by Livius90**
Automatic boot detection was merged from Technexion's u-boot repo based on the following discussion and patches.
https://github.com/TechNexion/u-boot-tn-imx/issues/6

SDHC auto boot-detection was tested in an [PICO-PI-IMX7 board](https://www.technexion.com/products/system-on-modules/evk/pico-pi-imx7/) and a custom carrier board for [PICO-IMX7D SoM](https://www.technexion.com/products/system-on-modules/pico/pico-imx7/). Moreover new migrated code can support the newest PICO-IMX7D SoM with 2GB DDR memory.

### CODE REVIEW

**Comment by otavio** [comment]
I am fine in considering a backport for this once U-Boot mainline apply this. Can you send it to their mailing list?

**Comment by Livius90** [comment]
Can you help what is the method of it and where can i found some rules about to submit any patches to mainline u-boot? I could found some old broken link about it from u-boot repo information pages, so these can not help in it.

**Comment by otavio** [comment]
See https://github.com/u-boot/u-boot/blob/master/README#L3283

**Comment by Livius90** [comment]
I submitted it in a patch: https://lists.denx.de/pipermail/u-boot/2022-August/492413.html

**Comment by otavio** [comment]
@fabioestevam can you review @Livius90 patch on u-boot mailing list?

**Comment by Livius90** [comment]
Is there any news about the review?

**Comment by Livius90** [comment]
@otavio @fabioestevam 
Is there any news about this pull request?

**Comment by Livius90** [comment]
@fabioestevam 
Please review the following patch series:
[[u-boot][master][PATCH 1/3] pico-imx7d: add support for 2GB memory SoMs](https://lists.denx.de/pipermail/u-boot/2022-December/502465.html)
[[u-boot][master][PATCH 2/3] pico-imx7d: add baseboard SD card boot detect](https://lists.denx.de/pipermail/u-boot/2022-December/502466.html)
[[u-boot][master][PATCH 3/3] pico-imx7d: update defconfigs of pico-imx7d baseboards](https://lists.denx.de/pipermail/u-boot/2022-December/502467.html)

**Comment by Livius90** [comment]
As i see it will be never to merged and you really do not care about the full functionality of i.MX boards in this u-boot repo. It is totally pointless to waiting for it, as i see.

**Pull request closed without merging**
